package org.league.app.database.entity.enums;

public enum EventType {

    TEAM_JOIN_REQUEST_REVOKED,
    PLAYER_INVITATION_REJECTED,
    TEAM_INVITATION_REJECTED,
    PLAYER_INVITED,
    PLAYER_JOINED,
    TEAM_JOINED,
    TEAM_LEFT,
    TEAM_CREATED,
    TEAM_DELETED,
    TEAM_LEFT_TEAM_DELETED,
    TEAM_KICKED_OUT,
    TEAM_ROLE_CHANGED,
    TEAM_INVITATION,

    MATCH_CONFIRMED,
    AWAITING_QR_CONFIRMATION,

    TEAM_PARTICIPATION,
    SOLO_PARTICIPATION,
    COMPETITION_WINNER,
}
